color0 #141312
color1 #ffb4ab
color2 #c9c7b7
color3 #c9c6be
color4 #c1c9bf
color5 #c9c7b7
color6 #c9c6be
color7 #e5e2df
color8 #939187
color9 #ffb4ab
color10 #c9c7b7
color11 #c9c6be
color12 #c1c9bf
color13 #c9c7b7
color14 #c9c6be
color15 #e5e2df

cursor                #e5e2df
cursor_text_color     #141312
background            #141312
foreground            #e5e2df
selection_foreground  #c9c6bc
selection_background  #48473f
active_border_color   #c9c7b7
inactive_border_color #48473f
url_color             #c9c7b7

active_tab_foreground   #313125
active_tab_background   #c9c7b7
inactive_tab_foreground #c9c6bc
inactive_tab_background #48473f
cursor_trail_color      #c9c6bc
