"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](base)\
$os\
$username\
[](bg:mantle fg:base)\
$directory\
[](bg:surface2 fg:mantle)\
$git_branch\
$git_status\
[](fg:surface2 bg:overlay1)\
$time\
[ ](fg:overlay1)\
$line_break\
$character"""

palette = "noctalia"

[os]
disabled = false
style = "bg:base fg:subtext1"

[os.symbols]
CachyOS = "󰣇"
Linux = "󰌽"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:base fg:subtext1"
style_root = "bg:base fg:subtext1"
format = '[ $user]($style)'

[directory]
style = "bg:mantle fg:subtext1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:surface2 fg:subtext1"
format = '[[ $symbol $branch ](fg:base bg:surface2)]($style)'

[git_status]
style = "bg:surface2 fg:subtext1"
format = '[[($all_status$ahead_behind )](fg:base bg:surface2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:overlay1 fg:base"
format = '[[  $time ]($style)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:subtext1)'
error_symbol = '[❯](bold fg:surface2)'
