-- T7 Dotfiles — Hyprland 0.56 Lua
-- Clean port from Niri rice. Intents: ~/T7 HYPRLAND MIGRATION/
-- Displays: defaults here; runtime ownership → t7-display (lid / HDMI).

hl.config({ autogenerated = false })

local terminal    = "kitty"
local fileManager = "nautilus"
local browser     = "$HOME/.local/bin/zen-browser"
local mainMod     = "SUPER"

----------------
---- MONITORS ----
-- Runtime authority: t7-display (systemd user service + reconcile).
-- Clamshell-safe static defaults: eDP DISABLED so reload never lights
-- a closed laptop panel. t7-display enables eDP only when policy allows.
----------------
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "0x0",
    scale    = 1,
})
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "1920x0",
    scale    = 1,
    disabled = true,
})
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

----------------
---- AUTOSTART ----
----------------
-- One call only: ensure daemon service + reconcile. No parallel watchers.
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("$HOME/.local/bin/t7-display ensure")
    hl.exec_cmd("$HOME/.local/bin/apply-noctalia-hypr-colors")
    hl.exec_cmd("$HOME/.local/bin/t7-keyboard apply")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("$HOME/.local/bin/t7-display ensure")
    hl.exec_cmd("$HOME/.local/bin/t7-keyboard apply")
end)

----------------
---- ENV ----
----------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "capitaine-cursors")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
-- Keyboard: Redragon K630 — ~/.config/xkb/t7-k630-v3.xkb
hl.env("XKB_DEFAULT_LAYOUT", "us")

----------------
---- LOOK / INPUT ----
----------------
-- Match Niri: gaps 16 outer, border 3, radius 0, compact dark shadow frame
hl.config({
    general = {
        gaps_in          = 8,
        gaps_out         = 16,
        border_size      = 3,
        col = {
            active_border   = "rgb(c9c7b7)",
            inactive_border = "rgba(201f1eaa)",
        },
        resize_on_border = true,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding         = 6,  -- fine round (was 0 square; keep subtle)
        rounding_power   = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled      = true,
            range        = 6,
            render_power = 2,
            offset       = { 2, 5 },
            color        = 0xcc000000,
        },
        blur = {
            enabled = false,
            size    = 3,
            passes  = 1,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
        smart_split    = false,
        smart_resizing = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper     = 0,
        disable_hyprland_logo       = true,
        disable_splash_rendering    = true,
        focus_on_activate           = true,
        middle_click_paste          = false,
        animate_manual_resizes      = true,
        animate_mouse_windowdragging = false,
    },

    input = {
        -- Dual-keyboard policy (do not set kb_file globally):
        --   laptop  → layout latam (Spanish Latin American)
        --   K630    → per-device kb_file (US base + ñ on key next to Enter)
        -- Virtual devices (GSR UI, Bluetooth AVRCP) must stay disabled so they
        -- never become "main" and steal layout / bind resolution.
        kb_file            = "",
        kb_layout          = "latam",
        kb_variant         = "",
        kb_options         = "",
        kb_model           = "pc105",
        numlock_by_default = true,
        follow_mouse       = 1,
        sensitivity        = 0,
        -- Binds match symbols (ñ, {) so Super+ñ works on both keyboards
        resolve_binds_by_sym = true,
        touchpad = {
            natural_scroll         = true,
            disable_while_typing   = true,
        },
    },


    binds = {
        workspace_back_and_forth = true,
    },
})

----------------
---- MOTION ----
-- Niri used ~320–380ms ease-out curves. Stock Hypr windowsOut (~speed 1.5)
-- feels heavy/old. Higher speed = faster; subtle popin, no bouncy springs.
----------------
hl.curve("outExpo",  { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("outCubic", { type = "bezier", points = { { 0.33, 1 }, { 0.68, 1 } } })
hl.curve("outQuad",  { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })

hl.animation({ leaf = "windows",     enabled = true, speed = 7,  bezier = "outExpo" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 7,  bezier = "outExpo",  style = "popin 92%" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 8,  bezier = "outCubic", style = "popin 96%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 7,  bezier = "outExpo" })
hl.animation({ leaf = "fade",        enabled = true, speed = 7,  bezier = "outQuad" })
hl.animation({ leaf = "fadeIn",      enabled = true, speed = 7,  bezier = "outQuad" })
hl.animation({ leaf = "fadeOut",     enabled = true, speed = 8,  bezier = "outCubic" })
hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "outQuad" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 7,  bezier = "outExpo",  style = "slide" })
hl.animation({ leaf = "layers",      enabled = true, speed = 7,  bezier = "outExpo" })
hl.animation({ leaf = "layersIn",    enabled = true, speed = 7,  bezier = "outExpo",  style = "fade" })
hl.animation({ leaf = "layersOut",   enabled = true, speed = 8,  bezier = "outCubic", style = "fade" })


----------------
---- DEVICES (keyboard map) ----
----------------
local t7_kb = os.getenv("HOME") .. "/.config/xkb/t7-k630-v4-full.xkb"

-- Noise / virtual keyboards: never "main", never type with these.
for _, name in ipairs({
    "gsr-ui-virtual-keyboard",
    "rz-b110w-(avrcp)",
    "video-bus",
}) do
    hl.device({
        name    = name,
        enabled = false,
    })
end

-- Laptop internal keyboard → latam only
hl.device({
    name      = "at-translated-set-2-keyboard",
    kb_layout = "latam",
    kb_variant = "",
    kb_options = "",
    kb_model  = "pc105",
    kb_file   = "",
})

-- Redragon K630 60% (Evision interfaces). Exact names — regex is unreliable here.
for _, name in ipairs({
    "evision-rgb-keyboard",
    "evision-rgb-keyboard-1",
    "evision-rgb-keyboard-2",
    "evision-rgb-keyboard-3",
    "evision-rgb-keyboard-4",
}) do
    hl.device({
        name       = name,
        kb_file    = t7_kb,
        kb_layout  = "",
        kb_variant = "",
        kb_options = "",
        kb_model   = "pc105",
    })
end

----------------
---- KEYBINDS ----
----------------
-- Noctalia
hl.bind(mainMod .. " + SPACE",     hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))
hl.bind(mainMod .. " + ALT + L",   hl.dsp.exec_cmd("qs -c noctalia-shell ipc call lockScreen lock"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call sessionMenu toggle"))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call wallpaper toggle"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("$HOME/.local/bin/next-wallpaper"))

-- Apps
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))

-- Window
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind("F11",             hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + T", hl.dsp.group.toggle())
hl.bind(mainMod .. " + B", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

-- Focus (arrows + 60% keys from Niri)
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + M",     hl.dsp.focus({ direction = "down" }))

-- Move window
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + K",     hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + L",     hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + J",     hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + M",     hl.dsp.window.move({ direction = "down" }))

-- Monitors
hl.bind(mainMod .. " + ALT + left",  hl.dsp.focus({ monitor = "l" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.focus({ monitor = "r" }))
hl.bind(mainMod .. " + ALT + up",    hl.dsp.focus({ monitor = "u" }))
hl.bind(mainMod .. " + ALT + down",  hl.dsp.focus({ monitor = "d" }))
hl.bind(mainMod .. " + SHIFT + CTRL + left",  hl.dsp.window.move({ monitor = "l" }))
hl.bind(mainMod .. " + SHIFT + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mainMod .. " + SHIFT + CTRL + up",    hl.dsp.window.move({ monitor = "u" }))
hl.bind(mainMod .. " + SHIFT + CTRL + down",  hl.dsp.window.move({ monitor = "d" }))

-- Workspaces 1–9
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "previous" }))

-- Super + scroll: workspaces  |  Super+Shift/Ctrl + scroll: move window
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + SHIFT + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + mouse_up",   hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + mouse_down",  hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + mouse_up",    hl.dsp.window.move({ workspace = "e-1" }))

-- Resize Super+ñ / Super+{ (+ Shift = height)
hl.bind(mainMod .. " + ntilde",
    hl.dsp.window.resize({ x = -80, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + braceleft",
    hl.dsp.window.resize({ x = 80, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + ntilde",
    hl.dsp.window.resize({ x = 0, y = -80, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + braceleft",
    hl.dsp.window.resize({ x = 0, y = 80, relative = true }), { repeating = true })

-- Mouse drag / resize
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Media / brightness → Noctalia IPC
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume increase"),     { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume decrease"),     { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume muteOutput"),   { locked = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume muteInput"),    { locked = true })
hl.bind("XF86AudioNext",         hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media next"),          { locked = true })
hl.bind("XF86AudioPrev",         hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media previous"),      { locked = true })
hl.bind("XF86AudioPlay",         hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media playPause"),     { locked = true })
hl.bind("XF86AudioPause",        hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media playPause"),     { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness increase"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness decrease"), { locked = true, repeating = true })

-- Screenshots
-- Ctrl+Shift+1 = region  |  2 = full  |  3 = window  |  Print = full
hl.bind("CTRL + SHIFT + 1", hl.dsp.exec_cmd("$HOME/.local/bin/t7-screenshot region"))
hl.bind("CTRL + SHIFT + 2", hl.dsp.exec_cmd("$HOME/.local/bin/t7-screenshot full"))
hl.bind("CTRL + SHIFT + 3", hl.dsp.exec_cmd("$HOME/.local/bin/t7-screenshot window"))
hl.bind("Print",            hl.dsp.exec_cmd("$HOME/.local/bin/t7-screenshot full"))

-- System
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprctl dispatch dpms off"))
hl.bind("CTRL + ALT + Delete",     hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

-- Lid → same brain as daemon/hotplug (never separate apply paths)
hl.bind("switch:on:Lid Switch",
    hl.dsp.exec_cmd("$HOME/.local/bin/t7-display auto"),
    { locked = true })
hl.bind("switch:off:Lid Switch",
    hl.dsp.exec_cmd("$HOME/.local/bin/t7-display auto"),
    { locked = true })

----------------
---- RULES ----
----------------
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "zen-no-max",
    match = { class = "zen" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "vesktop",
    match = { class = "vesktop" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "float-pavu",
    match = { class = "org.pulseaudio.pavucontrol" },
    float = true,
})
